name: Auto Update Profile

on:
  schedule:
    # Runs the workflow every day at midnight (adjust schedule as needed)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to trigger this manually

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Update the profile README dynamically
    - name: Update Profile
      run: |
        echo "Updating Profile README..."
        # Example: Append the latest date or other dynamic content
        echo "Last Updated: $(date)" > LAST_UPDATED.md
        echo "Last Update: $(date)" >> README.md

    # Commit and push changes
    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Access your saved token securely
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated profile update"
        git push
